# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.1
loader_version=0.18.1
loom_version=1.5.+

# Disable checksum validation for CI (GitHub Actions)
loom.disableDownloadChecksums=true

# Mod Properties
mod_version=0.6.2+1.21.11_WIP4
maven_group=com.sandymandy.pleasurehorizons
archives_base_name=Pleasure_Horizons

# Dependencies
fabric_version=0.128.2+1.21.11
geckolib_version=5.2.0
sbl_version=1.16.8
cloth_config_version=19.0.147
mod_menu_version=15.0.0
da_version=1.2.1
